version: '3.8'
services:
  app:
    build: .
    ports:
      - ${APP_PORT}
    depends_on:
      - ${DATABASE_NAME}
    environment:
      MONGO_URI: mongodb://${DATABASE_NAME}:27017/nestdb
    env_file:
      - .env
  mongo:
    image: ${DATABASE_NAME}:6
    container_name: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
