version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/nestdb
    env_file:
      - .env
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
